[package]
name = "mailgun-rs"
version = "0.1.4"
authors = ["Dongri Jin <dongrify@gmail.com>"]
description = "An unofficial client library for the Mailgun API"
edition = "2018"
repository = "https://github.com/dongri/mailgun-rs"
license = "MIT"
keywords = ["email","mailgun"]
documentation = "https://docs.rs/mailgun-rs"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.reqwest]
version = "0.11.2"
features = ["json", "blocking"]

[dependencies.serde]
version = "1.0.125"
features = ["derive"]
